# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:





# Install Apple Provisioning Profile
# Install an Apple provisioning profile required to build on a macOS agent
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles' # Options: secureFiles, sourceRepository
    provProfileSecureFile: 'MF_iOS_Apps_App__Dev_Prof.mobileprovision' # Required when provisioningProfileLocation == SecureFiles
    #provProfileSourceRepository: # Required when provisioningProfileLocation == SourceRepository
    #removeProfile: # Optional

#Install Apple Certificate
#Install an Apple certificate required to build on a macOS agent
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates.p12'
    keychain: 'temp' # Options: default, temp, custom
    

- task: Xcode@5
  inputs:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    signingOption: manual
    signingIdentity: $(APPLE_CERTIFICATE_SIGNING_IDENTITY)
    provisioningProfileUuid: $(APPLE_PROV_PROFILE_UUID)
    packageApp: true
    exportPath: 'output/$(SDK)/$(Configuration)'


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'test' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
    
       
# # Xcode
# # Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
# - task: Xcode@5
#   inputs:
#     #actions: 'build' 
#     #configuration: '$(Configuration)' # Optional
#     #sdk: '$(SDK)' # Optional
#     #xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace' # Optional
#     #scheme: # Optional
#     #xcodeVersion: 'default' # Optional. Options: 8, 9, 10, default, specifyPath
#     #xcodeDeveloperDir: # Optional
#     packageApp: 
#     #archivePath: # Optional
#     #exportPath: 'output/$(SDK)/$(Configuration)' # Optional
#     #exportOptions: 'auto' # Optional. Options: auto, plist, specify
#     #exportMethod: 'development' # Required when exportOptions == Specify
#     #exportTeamId: # Optional
#     #exportOptionsPlist: # Required when exportOptions == Plist
#     #exportArgs: # Optional
#     #signingOption: 'nosign' # Optional. Options: nosign, default, manual, auto
#     #signingIdentity: # Optional
#     #provisioningProfileUuid: # Optional
#     #provisioningProfileName: # Optional
#     #teamId: # Optional
#     #destinationPlatformOption: 'default' # Optional. Options: default, iOS, tvOS, macOS, custom
#     #destinationPlatform: # Optional
#     #destinationTypeOption: 'simulators' # Optional. Options: simulators, devices
#     #destinationSimulators: 'iPhone 7' # Optional
#     #destinationDevices: # Optional
#     #args: # Optional
#     #workingDirectory: # Optional
#     #useXcpretty: # Optional
#     #publishJUnitResults: # Optional


# variables:
#   scheme: ''
#   sdk: 'iphoneos'
#   configuration: 'Release'

# steps:
# - task: Xcode@5
#   inputs:
#     sdk: '$(sdk)'
#     scheme: '$(scheme)'
#     configuration: '$(configuration)'
#     xcodeVersion: 'default' # Options: default, 10, 9, 8, specifyPath
#     exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
#     packageApp: true
